config/routes.rb
Rails.application.routes.draw do

  # get 'items/create'

  devise_for :users
  resources :users, except: [:index] do
    resources :items, only: [:create, :destroy]
  end


  get 'welcome/index'
  root to: 'welcome#index'


end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  def days_left
     7 - (DateTime.now.to_date - created_at.to_date).to_i
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :items

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @user = current_user
    # @user = User.find(params[:id])
    # @items = @user.items
    @item = Item.new( item_params )
    @item.user = current_user
    # @new_item = Item.new

    # authorize @comment

    if @item.save
      redirect_to @user, notice: "Item was saved successfully."
    else
      flash[:error] = "There was an error saving the item. Please try again."
    end

    # respond_to do |format|
    #   format.html
    #   format.js
    # end
  end

  def destroy
    @user = current_user
    # @user = Item.find(params[:user_id])
    @item = @user.items.find(params[:id])

    #  authorize @item
     if @item.destroy
       flash[:notice] = "Item was removed."
      #  redirect_to @user
     else
       flash[:error] = "Item couldn't be deleted. Try again."
      #  redirect_to @user
     end

     respond_to do |format|
       format.html 
       format.js
     end

   end

  private

  def item_params
    params.require(:item).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @items = @user.items
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<h4>Add an item:</h4>
<%= form_for [user, item] do |f| %>
  <%= f.text_field :name, class: 'form-control', placeholder: "Enter item" %>
</br>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<tr id='item-<%= item.id %>'>
  <td><%= item.name %></td>
  <td><%= item.days_left %></td>
  <td><%= link_to "", [item.user, item], method: :delete, class: 'glyphicon glyphicon-trash', remote: true %></td>
</tr>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-' +<%= @item.id %>).fadeOut(1500);
<% else %>
  $('#item-' +<%= @item.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", welcome_index_path %></li>
        <% if current_user %>
          <li><%= link_to "Profile", user_path(current_user) %></li>
        <% end %>
        <div class="pull-right user-info">
          <% if current_user %>
            <!--Hello --> <%#= current_user.name || current_user.email %>
            <%#= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
            <%= link_to current_user.name || current_user.email, edit_user_registration_path %>
              <!--<span class="glyphicon glyphicon-user"></span> -->
            <%# end %>
            <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
              <span class="glyphicon glyphicon-log-out"></span>
            <% end %>
          <%# else %>
            <%#= link_to "Sign In", new_user_session_path %> <!--or -->
            <%#= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </div>
      </ul>
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="media">
      <div class="media-body">
        <h1 class="media-heading"><%= @user.name %></h1>
        <%= render partial: 'items/form', locals: { item: Item.new, user: @user } %>
      </div>
    </div>
  </div>
</div>

<h2><p class="text-center">To-do List</p></h2>
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Task</th>
        <th>Days Left</th>
        <th>Completed</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'items/item', collection: @items %>
    </tbody>
  </table>
</div>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1 class="text-center">Blocitoff</h1>
  <p class="text-center">A self-destructing to-do list to keep you focused on the things that really matter.</p>
  <p class="text-center">
    <% if user_signed_in? == false %>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
    <% end %>
  </p>
</div>